tasks:
  - name: Backend
    init: |
      python -m venv venv
      source venv/bin/activate
      pip install -r backend/requirements.txt
      cd backend && python seed_data.py
    command: |
      source venv/bin/activate
      cd backend
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  - name: Frontend
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm run dev -- --host 0.0.0.0

ports:
  - port: 8000
    onOpen: ignore
    visibility: public
  - port: 5173
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - dbaeumer.vscode-eslint
